packaging_format = 2

id = "flarum"
name = "Flarum"
description.en = "Next-generation forum made simple"
description.fr = "Forum de nouvelle génération, simplement"
description.de = "Forum der nächsten Generation leicht gemacht"

version = "1.8.11~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://flarum.org"
demo = "https://discuss.flarum.org/d/21101-demos-come-to-flarum"
admindoc = "https://docs.flarum.org"
code = "https://github.com/flarum/framework"
cpe = "cpe:2.3:a:flarum:flarum"
fund = "https://flarum.org/donate/"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "80M"
ram.build = "400M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/flarum"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Choose your password. It will be useful if logging in from YunoHost fails or is disrupted."
    help.fr = "Choisissez votre mot de passe. Il sera utile si la connexion via YunoHost échoue ou est perturbée."
    type = "password"

    [install.title]
    ask.en = "Choose a title for your forum"
    ask.fr = "Choisissez un titre pour votre forum"
    ask.de = "Wählen einen Titel für eure Internetforum"
    type = "string"
    example = "My forum"
    default = "My forum"

    [install.init_main_permission]
    help.en = "If set to 'visitors', it will be open to all visitors like any forum. If private, only the YunoHost server users can access it."
    help.fr = "Si défini sur 'visiteurs', le forum sera accessible à tous, comme pour tout forum. Si privé, seuls les utilisateurs du serveur YunoHost pourront y accéder."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    ask.de = "Wählen Sie eine Sprache"
    type = "select"
    choices = ["fr", "en", "de"]
    default = "fr"

[resources]

        # The main source is only used to auto-update the package
        [resources.sources.main]
        prefetch = false
        url = "https://github.com/flarum/framework/archive/refs/tags/v1.8.11.tar.gz"
        sha256 = "197bbd0c8c0651344cc9707ffebfaaa3c23b82e2deb9b0421f44d81e76335d23"
        autoupdate.upstream = "https://github.com/flarum/framework"
        autoupdate.strategy = "latest_github_tag"

        # The flarum source is the one actually being installed
        [resources.sources.flarum]
        url = "https://github.com/flarum/flarum/archive/refs/tags/v1.8.1.tar.gz"
        sha256 = "25ab0e3f44944ab478dd1076d4ada60a4f1a6255cb291423011d35b341f32570"
        autoupdate.upstream = "https://github.com/flarum/flarum"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-curl, php8.4-dom, php8.4-gd, php8.4-mbstring, php8.4-pdo-mysql, php8.4-tokenizer, php8.4-zip, php8.4-ldap"

    [resources.database]
    type = "mysql"
